### ISSUE TITLE
Not supported in IE, Edge, Ipad and iPhone

### ISSUE THREAD

**Issue by AvanishKumar008** [tsayen/dom-to-image#105]
#78 I am using your API. Your API working fine in all browser except IE, Edge, Ipad and iPhone. I do not test on Mac. 
SVG not working fine in all browser. Can you help me what should i do for it.

**Comment by tsayen** [comment]
hi, sorry, I xannot help you because I cannot test on any of the browsers you've listed. I don't have any windows or ios devices

**Comment by AvanishKumar008** [comment]
Hi @tsayen 
I tested on all browsers and, not working well on all listed browser and devises. It means this is issue in this code, you close my issue without fix.

**Comment by tsayen** [comment]
The readme states explicitly that this lib is tested in FF and Chrome. I
never promised you to support all the OSes and devices out there, only the
ones I can test on.

You can add Safari and other browser support, it's open source

**Comment by AvanishKumar008** [comment]
I am not talking about promise. I am talking about issue. If i found any solution for it i will help you. But it should be fix.

**Comment by Sadi-1992** [comment]
This issue should be reopened!

**Comment by vishal-px** [comment]
Hi

When I am trying to take a screenshot I getting image dataUrl in android device, But on iPhone / iPad image dataUrl getting blank.

Issue [Click to view video](https://www.dropbox.com/s/nub9dir082x12fn/Image%20uploaded%20from%20iOS.MOV?dl=0l)
Is there any solution for iPhone / iPad device?

Thanks.

**Comment by joselu1sc** [comment]
Hi,
I got an exception when I test on Edge: 


oops, something went wrong! [object Event]

[object Event]: {bubbles: false, cancelable: false, cancelBubble: false, currentTarget: Object, defaultPrevented: false...}

**Comment by MSCAU** [comment]
I just tried to use this in Edge and it doesn't work and there is no error in the console.
