### ISSUE TITLE
Promise is undefined in IE11

### ISSUE THREAD

**Issue by okravchuk** [tsayen/dom-to-image#108]
Hello,
I get error in Internet Explorer 11 when use 
Unhandled exception at line 2, column 266 in http://localhost:58880/dom-to-image.min.js

0x800a1391 - JavaScript runtime error: 'Promise' is undefined

domtoimage.toPng(node)
                .then(function (dataUrl) {
                    var img = new Image();
                    img.src = dataUrl;
                    document.body.appendChild(img);
                })
                .catch(function (error) {
                    console.error('oops, something went wrong!', error);
                });

**Comment by tsayen** [comment]
hi, IE is not supported by this lib

**Comment by tsayen** [comment]
you may try to supply Promise with sine polyfill, but there certainly will be some other problems

**Comment by okravchuk** [comment]
Why don't you use JQuery promises? - In this case your library would work in IE.

**Comment by tsayen** [comment]
this lib has no external dependencies and I would want to keep it that way.
why dont you try polyfill and see what happens?

**Comment by okravchuk** [comment]
Yeah, polyfill really brings other problems
![image](https://cloud.githubusercontent.com/assets/19709467/23952545/6e5decba-099a-11e7-81d8-3934bf1c371e.png)

**Comment by tsayen** [comment]
biggest problem is that ie does not support svg foreignObject tag, without
this feature lib does not work at all. And it cannot be fixed with polyfills

**Comment by joselu1sc** [comment]
Hi!, So, did anyone find a solution? Thanks!
