### ISSUE TITLE
error converting html to png

### ISSUE THREAD

**Issue by ghispi** [tsayen/dom-to-image#11]
asArray function throws error when arrayLike is null.
I've managed to patch it by simply adding check and returning empty array as a result.

**Comment by tsayen** [comment]
Hi, can you please post a stack trace?

**Comment by ghispi** [comment]
```
Uncaught (in promise) TypeError: Cannot read property 'length' of null
    at Object.asArray (dom-to-image.js:409:35)
    at dom-to-image.js:528:26
    at Array.forEach (native)
    at getCssRules (dom-to-image.js:527:29)
asArray								@ dom-to-image.js:409
(anonymous function)				@ dom-to-image.js:528
getCssRules							@ dom-to-image.js:527
Promise.resolve (async)
readAll								@ dom-to-image.js:509
resolveAll							@ dom-to-image.js:494
embedFonts							@ dom-to-image.js:191
Promise.resolve (async)
processClone						@ dom-to-image.js:109
(anonymous function)				@ dom-to-image.js:75
Promise.resolve (async)
cloneNode							@ dom-to-image.js:68
(anonymous function)				@ dom-to-image.js:92
Promise.resolve (async)
processClone						@ dom-to-image.js:109
(anonymous function)				@ dom-to-image.js:75
```

In general it was bootstrap 2 with jquery.flot chart inside. Though even if I converted chart canvas to image it still had the same problem.

I wasn't able to isolate it and replicate in test code.

**Comment by tsayen** [comment]
Thanks a lot. I think I'll be able to fix that on Monday, currently I'm
travelling and don't have access to keyboard.

**Comment by tsayen** [comment]
please check whether [this version](https://github.com/tsayen/dom-to-image/releases/tag/1.0.2) solves your issue

**Comment by tsayen** [comment]
feel free to reopen if problem is still there

**Comment by ghispi** [comment]
yes, this solved the issue, thank you
