### ISSUE TITLE
Support for CSS

### ISSUE THREAD

**Issue by chitgoks** [tsayen/dom-to-image#134]
hi, this is my sample html

`<div style="white-space: nowrap; position: absolute; color: rgb(255, 0, 0); background: rgba(255, 255, 0, 0.3); left: 83.5px; top: 53px; font-style: normal; font-variant: normal; font-weight: normal; font-stretch: normal; font-size: 18.75px; line-height: normal; font-family: Helvetica; display: block;" id="my-node" contenteditable="true">asdfafsafsafas</div>`

**Comment by tsayen** [comment]
hi, please put together a jsfiddle and reopen this issue then
