### ISSUE TITLE
printing node from iframe result in blank image or error

### ISSUE THREAD

**Issue by claudeberube** [tsayen/dom-to-image#145]
I would like to grab DOM content from an iframe. But, I am having issues with it.
The background images are not appearing.  Would this be because there set with inline styles?
![capturedynamicimage](https://user-images.githubusercontent.com/29046526/28896609-26f603ec-77ab-11e7-8837-c20e16211f31.png)
 
--
DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
Fixed with: domtoimage.toPng(iframeContent.documentElement.children[1])
-- 

var iframe = document.getElementById(iframeId);
var iframeContent = iframe.contentDocument || iframe.contentWindow.document;
...
domtoimage.toPng(iframeContent.documentElement.children[1]) { ...

**Comment by coder-strange** [comment]
@claudeberube what was the solution?

**Comment by Graxi** [comment]
Got the same...Is this resolved?

**Comment by Aterr** [comment]
Same here.
