### ISSUE TITLE
Is it possible to pass html string instead of DOM reference ?

### ISSUE THREAD

**Issue by anishj0shi** [tsayen/dom-to-image#152]
Hello,

I want to render a png image genereated out of an html string, i tried wrapping it in a div via javascript and passing this div to toPng method unfortunately i get a success callback with response data as "data;"

is there a specific to render such data ? or this kind of use case is not supported at all ?

REgards,
Anish

**Comment by tsayen** [comment]
currently only DOM nodes are supported as input. you'll have to create a node from your HTML string yourself by some other means, like https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

**Comment by anishj0shi** [comment]
Hello,

I created a dom element using innerhtml like 👍 
var x = document.createElement("div");
			x.innerHTML = sString; // html string
domtoimage.toPng(x).then(function(sDataUrl) {
				console.log(sDataUrl);
			});

//output : sDataUrl

Any idea why this behavior ?

**Comment by tsayen** [comment]
a jsfiddle or codepen would be helpful here :)
