### ISSUE TITLE
Only work in Chrome 61

### ISSUE THREAD

**Issue by Dinesh-Wasnik** [tsayen/dom-to-image#157]
### Browsers
Not workking in 
 [ ] Firefox 55 
 [ ] Safari 8  
 [ ] Internet explorer

**Comment by Dinesh-Wasnik** [comment]
I solved this issue myself.
As the element is created on the fly. Click event is not working above mention browser.
so what I did is append element in html and then click event is working.

domtoimage.toJpeg(document.getElementById('my-node'), { quality: 0.95 })
    .then(function (dataUrl) {
        var link = document.createElement('a');
        link.download = 'my-image-name.jpeg';
        link.href = dataUrl;
      $('body').append(link);  // I added this you can change the selector here.
       link.click();
    });

**Comment by smkart** [comment]
Is it working in IE , If so may I know which version of IE 

Any pollyfills you used to make it work with IE ?
