### ISSUE TITLE
how to use in safari ?

### ISSUE THREAD

**Issue by Ayana7** [tsayen/dom-to-image#166]
Safari is not supported, as it uses a stricter security model on <foreignObject> tag. Suggested workaround is to use toSvg and render on the server.`

Sorry，I can not understand it，how to use in dafari ?

**Comment by ciys** [comment]
@Ayana7 do you understand it now?

**Comment by oscarhandsome** [comment]
I also have an issue on iOS, when i'm saving or create new div with the image, can't see a new image.

**Comment by JaapBarnhoorn** [comment]
I'm experiencing the same bug. See this CodePen: https://codepen.io/anon/pen/WLQBLr using .toSvg.
When you open it in Safari the canvas screen is empty. However when you reload Safari twice, it suddenly starts working.

Is this something that is fixable @tsayen ?
