### ISSUE TITLE
Error when using .toPng

### ISSUE THREAD

**Issue by raed667** [tsayen/dom-to-image#169]
### Use case: description, code  

I'm using "domtoimage" with an angular 4 project. 

"domtoimage.toPng" worked fine for a while. Now it outputs an error .

Can you help me figure out what the error means ?

### Expected behavior

PNG export

### Actual behavior (stack traces, console logs etc)

![error_dom_to_image](https://user-images.githubusercontent.com/1442690/33015375-d1bbb804-cdea-11e7-87fe-3e8a463c8f20.PNG)

### Library version
2.6.0

### Browsers

- [ x ] Chrome 49+  
- [ x ] Firefox 45+

**Comment by timurbazarbaev** [comment]
I have the same issue. This issue occurs when i try to export leaflet map, and a stange thing, in my case it depends on leaflet container size. For example if itis smaller than 600px by width or height can't export, and   get this error, if it's bigger than 600px i can export with no errors

**Comment by raed667** [comment]
up?

**Comment by eddydg** [comment]
I have the same issue when trying to export my Mapbox container.

For my part, I think that the error comes from a nested URI encoding problem:

- The error only appears when I add the NavigationControl to the map. This component has buttons styled with a
`&quot;data:image/svg+xml;charset=utf8,%3Csvg%20viewBox%3D[...]%3C%2Fsvg%3E%0A&quot;`
URI background. Whenever I remove these backgrounds, the conversion works back.

 - Wrapping the URI with `encodeURI` in [`function makeImage(uri)`](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L459) fixes the problem for me: `image.src = encodeURI(uri);`

@RaedsLab Do you also have nested URIs? It could be two different issues.
@timurbazarbaev The AttributionControl, by default, is responsive and collapses when the map is less than 640px wide. It could be a coincidence but you could try to disable this control temporarily (and other controls if any) to see if it changes anything.

**Comment by amiceli** [comment]
I have the same error when I try to export an li element

**Comment by chen-cohen-5391** [comment]
I have the same problem..

When trying to create an image of a specific element it works fine, but when I try to use the element's parent (this is the only child of this element) it doesn't work.

**Comment by Syndesi** [comment]
Maybe the dataUri is encoded a second time and therefore isn't readable anymore.
