### ISSUE TITLE
Google Fonts

### ISSUE THREAD

**Issue by ussman** [tsayen/dom-to-image#17]
Hi,

May be its issue OR not 
but i have some fonts added from google URL within my web page and when i do get dom to image it didn't render actual font faces which are getting render on web page from google URL.

please let me know if you can help.

Regards
Usman Abdul Razzaq

**Comment by ussman** [comment]
![my-node](https://cloud.githubusercontent.com/assets/1112024/12068919/dd89ddac-b03a-11e5-942f-e20b28aa39d7.png)
this one is after DOM-TO-Image

![screen shot 2016-01-01 at 3 49 39 am](https://cloud.githubusercontent.com/assets/1112024/12068920/dd8fb268-b03a-11e5-9dae-7858302da657.png)
and this one is as its showing on web
hope now you will get understand me

thanks for your help :)

**Comment by tsayen** [comment]
Hi! Maybe your problem is related to #14?
Are you seeing any related output in browser console?

**Comment by tsayen** [comment]
closing for now - reopen if this issue still bothers you

**Comment by mbbertino** [comment]
Hello, I think I'm getting this same erro

- With the following GWFs loaded in the page
![screen shot 2016-08-22 at 8 53 11 am](https://cloud.githubusercontent.com/assets/6395112/17855287/f508071a-6845-11e6-984f-593b5b3bbd0a.png)

- And the following dom node that renders the fonts correctly. 
![screen shot 2016-08-22 at 8 53 06 am](https://cloud.githubusercontent.com/assets/6395112/17855300/0baffac2-6846-11e6-8ad2-5de37957a49b.png)

- Using the following code
``` js
var node = $('.overlay')[0]

domtoimage.toPng(node).then(function (dataUrl) {
        var img = new Image();
        img.src = dataUrl;
        document.body.appendChild(img);
    })
    .catch(function (error) {
        console.error('oops, something went wrong!', error);
    });
```

- I receive this rendered png
![screen shot 2016-08-22 at 8 52 59 am](https://cloud.githubusercontent.com/assets/6395112/17855412/a44bf380-6846-11e6-9c0d-00376eca834a.png)

Any ideas?
