### ISSUE TITLE
appear a bug called: 'Uncaught (in promise) '

### ISSUE THREAD

**Issue by Juliiii** [tsayen/dom-to-image#175]
### Use case: description, code  
![error](https://user-images.githubusercontent.com/23744602/34001890-2d34f4da-e12c-11e7-95e7-542923e2c668.png)
![code](https://user-images.githubusercontent.com/23744602/34001912-3c509136-e12c-11e7-873f-9b39ab5cca33.png)

### Expected behavior
i want the bug never happen again, because when it happen, my code will regard it as a failure so the loading status will never end which make my users can not use the other picture.just like this:
![image](https://user-images.githubusercontent.com/23744602/34002066-a1818132-e12c-11e7-83aa-a1b7938e0ea3.png)

### Actual behavior (stack traces, console logs etc)
the atcual behavior just like i say above. and the stack traces like this:(i think the bug may not be caused by dom-to-image, but i do not how to fix, beacuse it only happen sometimes)
![image](https://user-images.githubusercontent.com/23744602/34002222-0210f14a-e12d-11e7-8bfb-166d3ae1cab8.png)

### Browsers

- [x] Chrome 49+  
- [ ] Firefox 45+

**Comment by VinaykumarJeyshan** [comment]
Even Im getting same error for particular DIV..In other places it is working fine

**Comment by perry-mitchell** [comment]
For me this is occurring when trying to select the body. I'd like to image the entire page, so using `document.body` as the target element is necessary. If I select say the very first `<main>` element, that works, but attempting to perform this on the `<body>` breaks on all sites that I've tried.

**Comment by perry-mitchell** [comment]
So I've managed to get it to work on the `<body>` by using the `filter` method as described in the docs. This is quite ugly, but now works as it filters out whatever was causing the problem:

```javascript
import domToImage from "dom-to-image";

function filterNode(node) {
    if (node instanceof Text) {
        return true;
    }
    return [
        "div",
        "span",
        "p",
        "i",
        "strong",
        "main",
        "aside",
        "article",
        "pre",
        "code",
        "time",
        "address",
        "header",
        "footer"
    ].includes(node.tagName.toLowerCase()) || /^h[123456]$/i.test(node.tagName);
}

export function getBodyImage(body = document.body) {
    // @todo: Get data from S3 if it exists
    return domToImage
        .toJpeg(body, { quality: 70, filter: filterNode, bgcolor: "#fff", imagePlaceholder: "https://placem.at/places?w=500" });
}
```

UPDATE: Adding `"img"` to the above function breaks it in my case.. It seems that the images break it a lot of the time.

**Comment by Pree21** [comment]
Thanks @perry-mitchell, My issue fixed with your solution.
