### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by Syndesi** [tsayen/dom-to-image#187]
Hi,

I'm using this wonderfull easy-to-use library very often and since some time I can't see any activity or maintenance on this repository.
Therefore I think that this project should be forked so that new work can be integrated, but what do you think?

[![](https://api.gh-polls.com/poll/01C6GFMMQKGCJQ6YQQ3YFKZ4ZC/no%20fork)](https://api.gh-polls.com/poll/01C6GFMMQKGCJQ6YQQ3YFKZ4ZC/no%20fork/vote)
[![](https://api.gh-polls.com/poll/01C6GFMMQKGCJQ6YQQ3YFKZ4ZC/new%20fork)](https://api.gh-polls.com/poll/01C6GFMMQKGCJQ6YQQ3YFKZ4ZC/new%20fork/vote)

**Comment by tsayen** [comment]
Hi, as you probably can see, I don't really have time to maintain this lib currently. That's unfortunate, as I would like to do that, but for now I have some other duties that take up to 100% of my spare time. This situation may change in a month or two, but I cannot give any guarantee. 

I have some ideas on what could be improved in the lib code, most importantly, splitting that single file into ES6 modules, rewriting using `async/await` and new JS syntax. There is some work to be done around webfont support, and there are some fixes to make here and there. That's what I would do first when/if I get some time for this project.

Of course, anyone is free to fork this lib and change it the way it suits them, I have no problem with that :)

Thanks for using this lib, glad it (hopefully) helped someone solve some real world problem.

**Comment by Syndesi** [comment]
Hi,

thank you for your answer :D I think with all your great work (and idears) I'll stick to this library and just help to solve some issues. And the pull-request I'd send: I think I'll use this file internally until there is a official solution.
Thank you for your answer :)
