### ISSUE TITLE
Can I get a transparent image?

### ISSUE THREAD

**Issue by XiNiHa** [tsayen/dom-to-image#188]
Is it possible to generate image that has transparent background?

**Comment by Syndesi** [comment]
Hi @anesin1109 ,

yes that's possible. To demonstrate this, I created three nodes: One contained a transparent image, the two others contain red text (one of them have a explicit transparent background). Then I used dom-to-image and loaded the created images in front of another image:
![screenshot-2018-2-24 transparent-dom-to-image](https://user-images.githubusercontent.com/9903723/36629969-9333353e-195e-11e8-9f11-44ee9fc91cb7.png)

You can run this example yourself:
```shell
yarn install
yarn start
```

The website will be available under `localhost:8080`.
[transparent-dom-to-image.zip](https://github.com/tsayen/dom-to-image/files/1754317/transparent-dom-to-image.zip)

**Comment by Syndesi** [comment]
Hi,
can you close this issue or do you need any further help/examples? :)

**Comment by XiNiHa** [comment]
Oh, I'm sorry. I forgot to close the issue. It's my first issue that can be closed while using Github for 5+ years lol

**Comment by Syndesi** [comment]
No problem, I'm just glad that I could help you :)
