### ISSUE TITLE
Improvement: use getScreenshot method for Firefox

### ISSUE THREAD

**Issue by OEvgeny** [tsayen/dom-to-image#193]
### Use case: description, code  
Firefox has some feature to capture DOM out of the box. Here is the article: https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/getScreenshot

I didn't dig into `dom-to-image`, so I don't know how difficult it would be to implement. But I think that implementing such approach can improve things for Firefox. Although I'm not sure. 

Anyway, this aims to show what there is at least some opportunity for Firefox to do that. 

Thanks for the great work!

**Comment by ziadkh0** [comment]
The `getScreenshot` feature is on supported in chrome code (see the note at the bottom of the link article)
Which means it can't be used by web pages :disappointed:
