### ISSUE TITLE
Grayscale property blurr issue

### ISSUE THREAD

**Issue by vishaltatva** [tsayen/dom-to-image#199]
While using CSS grayscale and invert properties for image, the image is getting blurred, while original image is displayed perfectly

**Comment by Syndesi** [comment]
I think it's related to #195, but at this moment I can't test nor write any bugfix at all.
Have you tried the following things?
- capture only the image in its original size
- capture only the image in its original size with CSS grayscale applied
- capture the image which is painted to a canvas
