### ISSUE TITLE
compatibity with safari

### ISSUE THREAD

**Issue by Pistil-Studio** [tsayen/dom-to-image#20]
I and thx a lot for your job.
Do you will try to make a safari compatibility soon ?

**Comment by tsayen** [comment]
Hi. As far as I know there are no issues with Safari currently, so I assume this lib should run on Safari with no problem. The thing is I have no access to Safari (I'm on Ubuntu), therefore I cannot include it into automated tests.  
Are you experiencing any issues with this lib in Safari?

**Comment by prabhaav** [comment]
hi @tsayen trying it in Safari (10.0.1), the lib doesn't work :(

**Comment by Rainpia** [comment]
please support Safari as soon as possible, thanks

below is error message:
SecurityError (DOM Exception 18): The operation is insecure.
toDataURL
promiseReactionJob

**Comment by tsayen** [comment]
@Rainpia sorry, I don't have resources to support Safari

**Comment by Rainpia** [comment]
@tsayen , if you want, i can let you control my computer at the right time.

**Comment by tsayen** [comment]
well, thank you, but that doesn't look like a viable solution to me :)
