### ISSUE TITLE
Specify output image dimensions

### ISSUE THREAD

**Issue by cronoklee** [tsayen/dom-to-image#21]
It would be extremely useful to be able to optionally specify the dimensions for the output image and have the image rendered at a higher resolution than the DOM element itself. 

This would have numerous uses but would be particularly useful for printing the image afterwards. Printing at 72dpi (screen resolution) is not advisable!

One simple idea for making this happen is to scale the DOM element before rendering using the CSS **zoom **property or the CSS **transform **property. I attempted this but the bounding box for the element seems to remain the same, so while the elements do render larger, as expected, the image itself is cropped to the original size of the element, cutting out the bottom and right part of the element.

**Comment by tomgallagher** [comment]
+1 This would certainly be an enhancement

**Comment by tomgallagher** [comment]
Could you not wrap the cloned dom node in a wrapper div and then start the transform process? I was working on my own zoom function for something else the other day and the transform property worked OK for text and not so great for images/graphics.

**Comment by tsayen** [comment]
I think `zoom` property would be the way to go, I gotta check that

**Comment by stevie-p** [comment]
+1. This would be a useful feature for creating thumbshots with consistent width/height irrespective of browser width.
My workaround at the moment is to clone and render the element at the required size before passing to `domtoimage`:

    var clone = element.cloneNode(true);
    clone.setAttribute("style", "width: 640px; height: 480px;");
    document.body.appendChild(clone);
    domtoimage.toBlob(clone).then(function (blob) {
        clone.remove();
        /* Do something with the blob */
    }

**Comment by tsayen** [comment]
Hi, with recently added `width`, `height` and `style` options I think you can solve your issue. Feel free to reopen this issue otherwise

**Comment by cronoklee** [comment]
Looks great, thanks tsayen! I cant find any examples on how the style option works. I'm trying to double the size of the output but I'm not sure what syntax is expected:

`domtoimage.toBlob(el, {style:"transform:(scale(2,2))"})`

**Comment by tsayen** [comment]
`style` should be an object (see [this test](https://github.com/tsayen/dom-to-image/blob/master/spec/dom-to-image.spec.js#L311))

**Comment by cronoklee** [comment]
Thanks. It's a clever solution and it would work well but there is still an issue unfortunately. 

Is it possible to move the code that draws the output image boundaries, to **_after_** the new styles have been applied? If the boundries of the element are changed by the new styles, the resulting image remains the old size.

For example, `domtoimage.toBlob( $(el), { style: {'zoom':zoom} })` misses part of the element because it ignores the new zoomed size. Adding width and height in the rendering options helps slightly but it means that any text inside the element needs to be re-styled as it's changing the element width.

**Comment by tsayen** [comment]
Maybe try also to add `width` and `height` properties to options? Also, you might want to use `scale` instead of zoom and it should scale the text as well. Correct me if I'm wrong.

**Comment by cronoklee** [comment]
I looked into this a bit more and I think using JS `node.scrollWidth` and `node.scrollHeight` is actually the problem. 

If we use [getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect) to get the node's width & height, it should return the real dimensions after scaling/transforms, etc.

[More info here](http://stackoverflow.com/questions/5834624/retrieve-width-height-of-a-css3-scaled-element)

**Comment by tsayen** [comment]
just to make sure, does that screenshot somehow resemble your use case? (it's from a test I've just written)

![screenshot from 2016-04-25 20 28 52](https://cloud.githubusercontent.com/assets/1733236/14794462/8f2e4dce-0b24-11e6-94d4-b19cb29af174.png)

**Comment by tsayen** [comment]
concerning the `getBoundingClientRect()` - unfortunately it seems to return the same value. Maybe because this node was never actually rendered - since it's a clone of the original one, thus it's bounded rectangle was never calculated.

**Comment by cronoklee** [comment]
Thanks for looking into this tsayen, That is more or less what I have but I have a line of centered text outside the grey box which is to be included in the image. 

I made a [quick fiddle](http://jsfiddle.net/ndbjahty/1/) to show how `getBoundingClientRect()` behaves differently. CSS `zoom` doesnt work at all but `scale` calculated correctly.

I tried replacing all instances of  `.scrollWidth` in the src code to `.getBoundingClientRect().width` and it did help but the resulting image is still too small. My node is 300px wide and now I'm getting an image of 450px wide, (I'm expecting 600px) using `domtoimage.toBlob( $(el), { style: {'transform': 'scale(2)'} })`

**Comment by tsayen** [comment]
take a look at [this jsfiddle](https://jsfiddle.net/tsayen/Lqeehhoa/2/) - does it do what you want?

**Comment by cronoklee** [comment]
Almost. Mine is more [like this](https://jsfiddle.net/Lqeehhoa/3/). It should really just scale the dom node exactly without any restyling.

**Comment by tsayen** [comment]
that's a strange behavior (I mean the scaled text overflows). But if you [wrap it into a div](https://jsfiddle.net/tsayen/Lqeehhoa/4/), the problem is fixed

**Comment by cronoklee** [comment]
Thanks I'll try putting a wrapper on it in the morning  and see if it works

**Comment by cronoklee** [comment]
Hi tsayen,
Setting width and height and adding the top left origin and wrapping text nodes in a wrapper div has solved the problem! Thank you kindly for all your support. 

Can I suggest you add one more rendering option called "scale" which automatically sets these settings for users? It's a very powerful feature to be able to render DOM nodes at any resolution and as we have seen, this feature is not obvious or easy to use.

here's my final, working function for downloading a scaled image in case someone else wants to use it: ([FileSaver.js](http://purl.eligrey.com/github/FileSaver.js/blob/master/FileSaver.js ) is required)
`function downloadAsImg( el, filename, scale ){
	if( scale!=undefined ) var props = {
		width: el.clientWidth*scale,
		height: el.clientHeight*scale,
		style: {
			'transform': 'scale('+scale+')',
			'transform-origin': 'top left'
	  	}
	}
	domtoimage.toBlob( el, props).then(function (blob) {
		window.saveAs(blob, filename==undefined ? 'image.png' : filename);
	});
}`

**Comment by tsayen** [comment]
Hey, glad it worked for you :) The feature you're suggesting absolutely
makes sense.

**Comment by blasto333** [comment]
@tsayen 

Width, height, and style options are nice; but would love if we could render that image at specific browser width without having the user resize their browser (so media queries can be provided). 

html2canvas has this; but your library is faster and cleaner; but I cannot port from html2canvas unless I have a way to render the image with a certain width and also it would be great if we could render with media = printl

**Comment by michalzareba0001** [comment]
Had some issues to generate 10x bigger jpeg file, but it's finally working ;) Thank you!

My code:
`function generateJpeg() {
    var node = document.getElementById('baner_image');

    domtoimage.toJpeg(node, {
        quality: 0.99,
        width: node.clientWidth * 10,
        height: node.clientHeight * 10,
        style: {
            'transform': 'scale(10)',
            'transform-origin': '50% 50%',
        }
    })
        .then(function (dataUrl) {
            var link = document.createElement('a');
            link.download = 'yourbaner.jpeg';
            link.href = dataUrl;
            link.click();
        });
}`

**Comment by aryanbhatt-clvt** [comment]
How to increase the domnode size which we have captured through findDomNode?
