### ISSUE TITLE
The web will be unresponsive if i have many Font files.

### ISSUE THREAD

**Issue by HWWWWWT** [tsayen/dom-to-image#212]
### Use case: description, code  

 @font-face {
            font-family: 'Gugi';
            src: url('http://test2.yunzhan365.com/resourceFiles/editor/fonts/gugi-regular-webfont.woff');
        }
        @font-face {
            /* AmaticSC*/
            font-family: 'AmaticSC';
            src: url('http://test2.yunzhan365.com/resourceFiles/editor/fonts/amaticsc-regular-webfont.woff');
        }
....
more than 20 species！
### Actual behavior (stack traces, console logs etc)
When i use ```domtoimage.toPng()``` ,all the fontFamily files will be downloaded and the web will be unresponsive. I have to spend a lot of time to wait until it's finished.
### Library version
```"dom-to-image": "^2.6.0",```
```"vue": "^2.5.13",```
### Browsers

- [x] Chrome 49+  
- [x] Firefox 45+

**Comment by zhaoyu69** [comment]
Hello. Any information about that issue?

**Comment by JiaXinYi** [comment]
this fork version can solve it.
https://github.com/MMF-FE/dom-to-image
yarn add @yzfe/dom-to-image
