### ISSUE TITLE
'Promise' is undefined

### ISSUE THREAD

**Issue by cristian-dan** [tsayen/dom-to-image#23]
I get a 'Promise' is undefined error on : dom-to-image.min.js, Line: 5, Column: 9 
the line :    `return b = b || {}, Promise.resolve(a).then(function(a) {`

When running on IE 11.0.9600.18204 on Windows 7 x64

**Comment by cristian-dan** [comment]
ok, I found a Promise polyfill

**Comment by tsayen** [comment]
It's probably because IE [does not support Promises](http://caniuse.com/#search=Promise). Unfortunately, this lib will not work in IE (see [readme](https://github.com/tsayen/dom-to-image#source))

**Comment by tsayen** [comment]
Unless you use a polyfill :)

**Comment by cristian-dan** [comment]
it doesn't work with polyfill either :(

**Comment by tsayen** [comment]
what are you getting?

**Comment by cristian-dan** [comment]
nothing's happening

**Comment by tsayen** [comment]
you might also have a problem with [SVG foreignObject](http://caniuse.com/#search=foreignObject). I would recommend switching to Edge if possible.

**Comment by cristian-dan** [comment]
thanks! going to try it in a few minutes :D

**Comment by cristian-dan** [comment]
Eh  ... only Win10. I have to try it on another computer

**Comment by AlexanderRodecape** [comment]
So, how do you use the promise polyfill?  I've added the script, but I don't know where to put 
require('es6-promise/auto');

**Comment by VishuMuthreja** [comment]
Hi cristian-dan,

Is your issue resolved yet ? Because I have same issue as I am using dom-to-image library. I also added Promise-polyfill.js file, but still the issue is not resolved.

After adding Promise-polyfill, I am getting Invalid State error.

Can you please confirm if this issue has been solved or not yet.

**Comment by bikash203** [comment]
I am Getting Promise' is undefined issues in IE browser, anyone can help - SCRIPT5009: 'Promise' is undefined, File: dom-to-image.js.

**Comment by bikash203** [comment]
I am Getting Promise' is undefined issues in IE browser, anyone can help - SCRIPT5009: 'Promise' is undefined, File: dom-to-image.js.
