### ISSUE TITLE
Issue with SVG rect in Chrome

### ISSUE THREAD

**Issue by newtriks** [tsayen/dom-to-image#24]
Running the following example doesn't appear to render `<rect>` in **Chrome** (_Version 48.0.2564.116 (64-bit)_):

http://jsfiddle.net/newtriks/cj82dupn/

I can confirm it does render fine in **FireFox** (_Developer Version - 46.0a2 (2016-03-07)_).

**Comment by newtriks** [comment]
@tsayen no problem. I've narrowed it down to [`cloneStyle()`](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L122). If this is not called e.g. comment out [Line 113](https://github.com/tsayen/dom-to-image/blob/master/src/dom-to-image.js#L113) then it works. 

Testing with other SVG shapes with and without **inline** styles also work without the need to clone the styles both in FF and Chrome. However styles are not copied when styling the SVG shapes using styles either from within a `<style>` tag or via an external style sheet.

**Comment by tsayen** [comment]
Thanks a lot for investigating this, @newtriks

**Comment by newtriks** [comment]
@tsayen no worries. I'll have a try with your fix today and feedback if I see any further issues. Thank you.
