### ISSUE TITLE
bug？iframe nothing？

### ISSUE THREAD

**Issue by hktalent** [tsayen/dom-to-image#270]
bug？iframe nothing？
#145 
```
var iframeContent = $(o.contentDocument || o.contentWindow.document).find("div.box")[0];
	domtoimage.toJpeg(iframeContent,{ quality: 0.65 }).then(function (dataUrl)
	{
			var link = document.createElement('a');
			link.download = id + '.jpeg';
			link.href = dataUrl;
			link.click();
	});
```
![image](https://user-images.githubusercontent.com/18223385/51168773-3064ca80-18e5-11e9-93df-dcf2221bb3d7.png)

save：
![image](https://user-images.githubusercontent.com/18223385/51168838-5c804b80-18e5-11e9-88c8-d68e896b1b78.png)

**Comment by Adondriel** [comment]
have you tried attaching to a dom item, inside of the iframe?

**Comment by hktalent** [comment]
ok @Adondriel
