### ISSUE TITLE
toJpeg() 方法导致黑屏的问题

### ISSUE THREAD

**Issue by lxg0** [tsayen/dom-to-image#275]
在toJpeg()方法里找到以下：  

canvas.toDataURL('image/jpeg',

改为：
canvas.toDataURL('image/jpg',

黑屏问题得到解决。

- [ ] Chrome 71 
- [ ] Nightly 66

**Comment by tsayen** [comment]
sorry, I don't understand you, please write in English

**Comment by lxg0** [comment]
Black screen problem caused by toJpeg () method:

Find the following in the toJpeg () method:
canvas.toDataURL('image/jpeg',
Change to
canvas.toDataURL('image/jpg',

**The black screen problem has been solved.**
