### ISSUE TITLE
IE11 support, and hard to trace error when exception happens

### ISSUE THREAD

**Issue by allenhwkim** [tsayen/dom-to-image#28]
I got this message when I test on windows

![image](https://cloud.githubusercontent.com/assets/1437734/14123356/1f0f420c-f5ce-11e5-93a1-9fe32420d825.png)

From the message above, I have no clue which line gave that error message.

The function I ran was 
```
function () {
      domtoimage.toPng(document.querySelector('body'))
        .then(function (dataUrl) {
          var img = new Image();
          img.src = dataUrl;
          document.body.appendChild(img);
        })
        .catch(function (error) {
          console.error('OOOOOOOOPS, something went wrong!', error);
        });
    }
```

Is there any error tracing method in your application?

**Comment by allenhwkim** [comment]
The function I ran was 
```
function () {
      domtoimage.toPng(document.querySelector('body'))
        .then(function (dataUrl) {
          var img = new Image();
          img.src = dataUrl;
          document.body.appendChild(img);
        })
        .catch(function (error) {
          console.error('OOOOOOOOPS, something went wrong!', error);
        });
    }
```

**Comment by tsayen** [comment]
If I'm not mistaken, you're getting a DOMException there. I'm not familiar with IE console, but it looks like you can view a stack trace there. The general reason for error would probably be that **IE is not supported by this lib**, see #23
