### ISSUE TITLE
image have offsetX

### ISSUE THREAD

**Issue by cailongl** [tsayen/dom-to-image#281]
### Use case: description, code  
```js
unmake = async () => {
    // TODO
    try {
      const element = document.getElementById('artboard-container')
      const {width, height} = element.getBoundingClientRect()
      const dataUrl = await dom2image.toJpeg(element, {
        quality: 0.95,
        width,
        height,
        filter: ele => ele.tagName !== 'IMG' && !['wave-box-tools', 'artboard-cursor', 'artboard-grid'].includes(ele.id)
      })
      const link = document.createElement('a')
      link.download = 'my-image-name.jpeg'
      link.href = dataUrl // URL.createObjectURL(blob)
      link.click()
    } catch (e) {
      console.log(e)
    }
  }
```

### Expected behavior
I want get a jpeg is not offsetX, and it full with the width. 
The dom that i want get  is center of screen.but i want the image not with offsetX 
### Actual behavior (stack traces, console logs etc)

![image](https://user-images.githubusercontent.com/21746104/54986467-a8d6be80-4fed-11e9-8946-7cee9d296ad9.png)

### Library version
"dom-to-image": "^2.6.0",

### Browsers

- [x] Chrome 49+

**Comment by Homer1011110** [comment]
I have the same issue

Here is my solution, I hope this will be helpful for you

```javascript
// use style option to set margin to 0
domtoimage.toSvg(this.ref, {
    quality: 1,
    style: {
        margin: 0
    }
})
```

**Comment by cailongl** [comment]
@Homer1011110 thanks a lot, it worked.

**Comment by cesswhite** [comment]
> I have the same issue
> 
> Here is my solution, I hope this will be helpful for you
> 
> ```js
> // use style option to set margin to 0
> domtoimage.toSvg(this.ref, {
>     quality: 1,
>     style: {
>         margin: 0
>     }
> })
> ```

Thank you!
