### ISSUE TITLE
如果没有渲染，不能转换成功。

### ISSUE THREAD

**Issue by lxg0** [tsayen/dom-to-image#283]
![image](https://user-images.githubusercontent.com/32631258/56778125-66301e00-6807-11e9-9cdb-0e0e2e62e6c1.png)
结果：
![image](https://user-images.githubusercontent.com/32631258/56778143-7fd16580-6807-11e9-8d77-ebd3efa34d35.png)
![image](https://user-images.githubusercontent.com/32631258/56778189-ad1e1380-6807-11e9-9772-f2d6162e6ffb.png)

![image](https://user-images.githubusercontent.com/32631258/56778157-8e1f8180-6807-11e9-8860-592f3ad51aaf.png)
结果：
![image](https://user-images.githubusercontent.com/32631258/56778165-9d9eca80-6807-11e9-9240-f2d69ae5a3a4.png)

- [ ] Chrome 49+  
- [ ] Firefox 45+

**Comment by tsayen** [comment]
sorry, I don't understand the issue, please write in English
