### ISSUE TITLE
property 'cloneNode' of undefined     at makeNodeCopy

### ISSUE THREAD

**Issue by fmm1992** [tsayen/dom-to-image#288]
Hi!Why do I keep reporting this mistake?
   Uncaught (in promise) TypeError: Cannot read property 'cloneNode' of undefined
    at makeNodeCopy
Here's my code：
      domtoimage.toBlob(document.getElementById('wrapper'))
          .then(function (blob) {
            console.log(blob)
              // window.saveAs(blob, 'my-node.png');
          });

**Comment by tsayen** [comment]
please stop spamming
