### ISSUE TITLE
DOMException: "Index or size is negative or greater than the allowed amount"

### ISSUE THREAD

**Issue by saravntbe** [tsayen/dom-to-image#296]
### Use case: description, code  
Getting DOMException: "Index or size is negative or greater than the allowed amount" in firefox

### Actual behavior (stack traces, console logs etc)
DOMException: "Index or size is negative or greater than the allowed amount"
### Library version
2.6.0
### Browsers

- [ ] Chrome 49+  
- [X] Firefox 45+  

[similar Issue](https://github.com/tsayen/dom-to-image/issues/228)

**Comment by vitoo** [comment]
Same error, same version and firefox 68

**Comment by vitoo** [comment]
My issue was that the DOM node was not visible

So i add a check, with jQuery : 

``` javascript
if($('#element').is(':visible')){

 domtoimage.toPng( ... )

}
```
