### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by Starloss** [tsayen/dom-to-image#315]
Hi, im getting problems with CORS policy when i try to draw an image that is in the aws (the profile photos), i attach the problem log and the code where i use the dom-to-image.
![1](https://user-images.githubusercontent.com/43561472/67006993-68877c80-f0b4-11e9-981e-a16545542dfd.PNG)
![2](https://user-images.githubusercontent.com/43561472/67006994-68877c80-f0b4-11e9-8b04-20401bd4cf18.PNG)

The problem isn't the server, because i use an http request without this library and works fine.

Edit: When i use only users without profile image, the library works perfect!

**Comment by grimace** [comment]
try this:

```       
       let options = { "cacheBust":true }
       domtoimage.toJpeg(node, options)
```

**Comment by Starloss** [comment]
> try this:
> 
> ```
>        let options = { "cacheBust":true }
>        domtoimage.toJpeg(node, options)
> ```

Works perfect, now the screenshot takes all the images without any problem, thanks!

**Comment by rutikwankhade** [comment]
not working for me. is there any other solution?
