### ISSUE TITLE
can I  use this package in node.js with jsDom simulating real DOM in HTML document ？

### ISSUE THREAD

**Issue by NoTalk-ly** [tsayen/dom-to-image#321]
> ### Use case: description, code
can I  use this package in node.js with jsDom simulating real DOM in HTML document ？
> ### Expected behavior
ok
> ### Actual behavior (stack traces, console logs etc)
I dont know
> ### Library version
> I'm using the latest version.
> ### Browser
> * [ ]  Chrome 49+

**Comment by patarapolw** [comment]
So, can you? How?

**Comment by NoTalk-ly** [comment]
> So, can you? How?

maybe not, I guess
