### ISSUE TITLE
Getting node from DOMParser results in a data string of 'data:,'

### ISSUE THREAD

**Issue by sjcrook** [tsayen/dom-to-image#349]
Dynamically creating a DOM using DOMParser, I was expecting a successful render.  See fiddle.

[jsfiddle](https://jsfiddle.net/tsayen/ojb1b31r/2/)

**Comment by sjcrook** [comment]
forgot to add options object to toPng

**Comment by Nervniyak** [comment]
Wait, what options did you add?
I also have this 
`domtoimage.toPng(el).then(function (dataUrl) { });`
returning `'data:,'`

**Comment by Summer-andy** [comment]
domtoimage
          .toPng(dom { quality: 0.5 })
          .then(function(dataUrl) {
            console.log(dataUrl);
            var link = document.createElement('a');
            link.download = `card.jpeg`;
            link.href = dataUrl;
            link.click();
          });

the dataUrl is data:,
