### ISSUE TITLE
Capturing vertical half image on Chrome Browser

### ISSUE THREAD

**Issue by lavchauhan** [tsayen/dom-to-image#35]
Issue 

> Promise is Undefined

 on  Safari Browser  (version [5.1.7)

> Capturing vertical half image on Chrome Browser  (version  49.0.2623.112)

var mainDiv = document.getElementById('mainDiv');
var canvas = document.createElement('canvas');
canvas.width = mainDiv.scrollWidth;
canvas.height = mainDiv.scrollHeight;

domtoimage.toPng(mainDiv).then(function (pngDataUrl) {
            console.log(pngDataUrl);
}).catch(function (error) {
             console.log("OOPS, something went wrong!.");
});

Perfect working on Mozila Browser  

I did not get full image on chrome browser 
Displaying White Space below portion 

![report_14622551420011](https://cloud.githubusercontent.com/assets/18712954/14976336/52675872-1128-11e6-9eca-e5e51186f6f1.png)

**Comment by tsayen** [comment]
You safari version (is it 5.x.x?) is way too old for sure. Concerning
Chrome - please provide a jsfiddle that shows the problem.

**Comment by lavchauhan** [comment]
https://jsfiddle.net/g2ocv6qL/

**Comment by tsayen** [comment]
@lavchauhan something is wrong with your example: `ReferenceError: domtoimage is not defined`

**Comment by ollieshmollie** [comment]
Was having a similar problem in Chrome trying to download JPEG of a centered container div (margin: 0 auto). Taking away all margins made it work perfectly.

**Comment by DetectiveBox** [comment]
I met a problem, too. My error message is " domtoimage is not defined". And I have not found the solution.

**Comment by morteza-gho** [comment]
@DetectiveBox Did you find any solution?

**Comment by roma-glushko** [comment]
Here is the solution for "margin: 0 auto" issue:
https://github.com/tsayen/dom-to-image/issues/197#issuecomment-380557489

Replacing it with flexbox-based solution seems to help to take the right rendering.
