### ISSUE TITLE
Getting node from DOMParser results in a data string of 'data:,'

### ISSUE THREAD

**Issue by Summer-andy** [tsayen/dom-to-image#363]
domtoimage
          .toPng(domRef.current, { quality: 0.5 })
          .then(function(dataUrl) {
            console.log(dataUrl);
            var link = document.createElement('a');
            link.download = `card.jpeg`;
            link.href = dataUrl;
            link.click();
          });

   dataUrl is 'data:,'

**Comment by axtlive** [comment]
I met the same case, have you solve it ?

**Comment by Summer-andy** [comment]
yeah, i use other plugin to replace it.

**Comment by axtlive** [comment]
I found the reason finally，for the dom u choose to use must be in the document (can be seen in page ) ，otherwise U will get 'data:; ' ，if the dom were create by using 'document. createElement' the dom just in the  memory ，not in document(page)

**Comment by Summer-andy** [comment]
good！

**Comment by axtlive** [comment]
他妈的，中国人，都在上海，讲锤子英语。

**Comment by Summer-andy** [comment]
哈哈.
