### ISSUE TITLE
error in trying to capture body

### ISSUE THREAD

**Issue by elewinso** [tsayen/dom-to-image#42]
I have just downloaded the library.
I am hosting it on an apache server I have installed on my machine.
I am injecting the javascript to a given via the console
`var url='https://guest.supporttip.com/static/tipcms/js/dom-to-image.min.js';var head=document.getElementsByTagName("head")[0];var script=document.createElement("script");script.src=url;head.appendChild(script);`

and then I try to run the code from the readme:
```
var node = document.body;

domtoimage.toPng(node)
    .then(function (dataUrl) {
        var img = new Image();
        img.src = dataUrl;
        document.body.appendChild(img);
    })
    .catch(function (error) {
        console.error('oops, something went wrong!', error);
    });
```

I have tried this with several pages and it fails more often than not. Can someone assist?

**Comment by tsayen** [comment]
what error are you getting? can you put together a JSFiddle?

**Comment by elewinso** [comment]
I sorry, this was 2 months ago already, I don't remember.
we opted for using the chrome api instead.

**Comment by tsayen** [comment]
OK, no problem :)
