### ISSUE TITLE
How to keep ratio without adding blank space around the image

### ISSUE THREAD

**Issue by equinusocio** [tsayen/dom-to-image#460]
### Use case: description, code  

I have a fluid element on the page which has `width: 100%` and `aspec-ratio: 16/9` css properties applied. When exporting the element using `toPNG()` if i set a width of `2000` the image results in almost empty space.

The target element still the same size rendered on the page, so width is not applied to the element itself but just to the image canvas. The image below show a PNG generated with `width` set to `2000`, but the real content is the same size as it was when rendered on the page, instead of filling the whole canvas.

![pattern](https://github.com/tsayen/dom-to-image/assets/10454741/6eac2ecb-b5e0-4017-baa0-7d331a8b6305)

My options
```js
{
  width: 2000,
  height: 2000 * (9 / 16),
  bgcolor: 'transparent',
},
```

### Expected behavior

The target element should be the size specified inside options

### Actual behavior (stack traces, console logs etc)

Target element should be the size specified when rendered as image.

### Browsers

- [x] Chrome 49+  
- [x] Firefox 45+

**Comment by forever0714yuan** [comment]
你好，我已收到你的来信。辛苦了！！
