### ISSUE TITLE
The internal picture is blank

### ISSUE THREAD

**Issue by wsl0520** [tsayen/dom-to-image#463]
Under the premise that the image has been loaded, the blank space in the img tag inside the Dom element in the image generated on ios,but it works on Android phones. May I ask what causes it?
expect
<img width="468" alt="image" src="https://github.com/tsayen/dom-to-image/assets/49120298/63259263-75e4-4694-895e-70dd67bb1bd2">
actual
<img width="472" alt="image" src="https://github.com/tsayen/dom-to-image/assets/49120298/5bb2d92f-dc6e-426d-927a-4f6799c1d34c">

-  iPhone 13 pro  iOS16.6

**Comment by jifafa484** [comment]
please How was it resolved

**Comment by jifafa484** [comment]
怎么解决的

**Comment by learner-dhx** [comment]
> 怎么解决的

[https://github.com/qq15725/modern-screenshot](url)
