### ISSUE TITLE
Could you release the latest version on npm?

### ISSUE THREAD

**Issue by kennynaoh** [tsayen/dom-to-image#49]
Hello @tsayen ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
But I need some help.
Because I saw the latest version on [github](https://github.com/tsayen/dom-to-image) is v2.5.0, the latest version on [npm](https://www.npmjs.com/package/dom-to-image) is v2.4.0.
Could you help me release the latest version on npm?
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8589

**Comment by tsayen** [comment]
done :)

**Comment by kennynaoh** [comment]
Thanks!
