### ISSUE TITLE
The suggestion about js file

### ISSUE THREAD

**Issue by kennynaoh** [tsayen/dom-to-image#52]
Hello @tsayen ,
I am the member of cdnjs project.
We want to host this library.
But there are different naming in `src` and `dist` file in version `0.0.1`~`0.0.5`.(`domvas.js`)
What's your suggestion about changing the name from `domvas` to `dom-to-image` or keeping the same naming.
Thanks for your help!

https://github.com/cdnjs/cdnjs/issues/8589
https://github.com/cdnjs/cdnjs/pull/8701

**Comment by tsayen** [comment]
Hi. I'm afraid I don't fully understand what you're asking about. This lib was originally a fork, and the main file could be called domvas.js. But later I renamed it.

**Comment by kennynaoh** [comment]
So you mean `domvas` is the same as `dom-to-image`?
Thanks!

**Comment by tsayen** [comment]
no, domvas is a separate project, this lib is originally it's fork

**Comment by kennynaoh** [comment]
Because `dom-to-image` doesn't exist in version 0.0.1 on [github](https://github.com/tsayen/dom-to-image).
I think we don't need to add this version, right?
And also the `src/domvas` in version 0.0.2~0.0.5, right?
Thanks!

**Comment by tsayen** [comment]
Well, I cannot modify this repo's history, cause it would be a mess. If that's what you're asking for, I can't do that.
