### ISSUE TITLE
Problem with loading fonts

### ISSUE THREAD

**Issue by gen4sp** [tsayen/dom-to-image#55]
I have this lines in my css

```
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(../fonts/glyphicons-halflings-regular.eot);
  src: url(../fonts/glyphicons-halflings-regular.eot?#iefix) format('embedded-opentype'), url(../fonts/glyphicons-halflings-regular.woff) format('woff'), url(.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.ttf) format('truetype'), url(.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular) format('svg');
}
```

but dom-to-image trying to get it by this url
```
http://localhost:9000/styles/.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.ttf
```

**Comment by tsayen** [comment]
That should probably be one of the URLs it's trying to get (it should try to download every font file you have mentioned there in definition). One of the URLS in your `@font-face` declaration is this: `url(.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.ttf) format('truetype')`, so lib will try to resolve the URL against the stylesheet URL (and URL gets resolved to `http://localhost:9000/styles/.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.ttf`) and get the file. That actually seems legit. Am I missing something wrong here?

**Comment by gen4sp** [comment]
Yes, my fault, there is url(.spd-editor-.spd-editor-/fonts/glyphicons-halflings-regular.ttf), i miss that. Sorry for false alarm.
