### ISSUE TITLE
node rendering is slow - external fonts?

### ISSUE THREAD

**Issue by tomeraz** [tsayen/dom-to-image#62]
Hi,

I'm trying to render a small empty div, inside a large application.
```
<div
   class="src-editor-components-Elements-_index_elements-component_LDZYp"
   style="transform: scale(0.6); transform-origin: 0px 0px 0px; width: 1024px; height: 768px;">
</div>
```
The div's style is also almost empty:
```
{
bottom: -309.203px;
height: 768px;
left: 0px;
overflow-x: hidden;
overflow-y: hidden;
position: absolute;
right: -411.609px;
top: 0px;
width: 1024px;
z-index: 40;
perspective-origin: 512px 384px;
transform: matrix(0.6, 0, 0, 0.6, 0, 0);
transform-origin: 0px 0px;
}
```

The dom-to-image result svg compiled by dom-to-image contains a lot of fonts which do not reside inside the div styles.

So there are a lot of external fonts requests, even though they are not used within the div style.

The app uses [auth0 service](https://github.com/auth0/node-auth0), a single sign on service.

The requests made by dom-to-image are for fonts of auth0.

Is dom-to-image downloading fonts that are outside the rendered node style?

Any ideas why?
Any thoughts how to make it faster?

Thanks!

**Comment by cronoklee** [comment]
Yes, there is [currently a bug](https://github.com/tsayen/dom-to-image/issues/37) which loads all fonts on the page several times regardless of weather they are used in the actual node being rendered. I believe tsayen is aware of it and is planning a fix

**Comment by cronoklee** [comment]
If you dont need font rendering at all, you could try removing the line `.then(embedFonts)` in the `toSvg` function.

**Comment by tomeraz** [comment]
Thanks.


I do need font rendering as I need an exact snapshot of the dom node.



Tomer



From: cronoklee

Sent: Thursday, September 22, 12:59

Subject: Re: [tsayen/dom-to-image] node rendering is slow - external fonts? (#62)

To: tsayen/dom-to-image

Cc: tomeraz, Author



If you dont need font rendering at all, you could try removing the line .then(embedFonts) in the toSvg function.

**Comment by tsayen** [comment]
closing this in favor of #37
