### ISSUE TITLE
Crash on m.facebook.com

### ISSUE THREAD

**Issue by vrgomes** [tsayen/dom-to-image#68]
### Use case: description, code

Try to take an image from https://m.facebook.com/home.php. 

```
            domtoimage.toPng($('#body').get(0))
                .then(function (dataUrl) {
                    window.open(dataUrl);
                })
                .catch(function (error) {
                });
```
### Expected behavior

Generate the image in a new window.
### Actual behavior

It gives an error on console and don't work.
### Library version

2.5.2
### Browsers
- [ ] Chrome 49+

**Comment by tsayen** [comment]
Hi, please post the stack trace.

**Comment by tsayen** [comment]
Anyway, you're probably hitting a [CORS error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS). Issues like that were already closed here.  

Apart from that, making screenshots of other people's pages is not this lib's intended use case, and will likely fail for reasons that I don't control. I should probably make this more clear in the docs.  

If what you're getting is something other than CORS error, we'll take a closer look at the issue.

**Comment by vrgomes** [comment]
In console it only shows: 
home.php:1 Uncaught (in promise) Event {isTrusted: true, type: "error", target: null, currentTarget: null, eventPhase: 0…}

The problem is that if it's a small area (like a post) it works. But if it's iin the facebook feed with very posts it crashes. Don't look like a CORS error.

**Comment by tsayen** [comment]
The reason you get an error on larger element might be that the larger element is more likely contain an image - which, being served from facebook.com, breaks rendering. I'm closing this issue for now. Feel free to reopen if you can come up with a more concrete code that demonstrates the problem
