### ISSUE TITLE
Filter Blur don't work

### ISSUE THREAD

**Issue by miyakedev** [tsayen/dom-to-image#72]
converting an image with blur filter to canvas apparently did not work.

Any suggestions?

**Comment by tsayen** [comment]
hi, please use the issue template

**Comment by ghost** [comment]
> converting an image with blur filter to canvas apparently did not work.
> 
> Any suggestions?

Same problem here. Did you manage to fix?

**Comment by chocopiano** [comment]
Same problem here. Did someone fix it? Thx!
