### ISSUE TITLE
Scroll issue

### ISSUE THREAD

**Issue by sarath-sasikumar** [tsayen/dom-to-image#98]
When the content to be pasted has scrollable content (with overflow set to auto in css) then the image which is formed should ideally have the entire content in the scroll panel .

In the present scenario the image is very awkward as it also has the scroll bar. Rather it should have the entire contents of the scrollabe div

**Comment by jacobmarshall** [comment]
Would you be able to provide an example of the HTML you're attempting to convert to an image. I think I've experienced similar issues with a particular website & how it was structured.

**Comment by tsayen** [comment]
@sarath-sasikumar please provide a jsfiddle to illustrate your point and reopen this issue if you still have the problem
